### ISSUE TITLE
Updating System?

### ISSUE THREAD

**Issue by umren** [mvdleden/electric-bastionland-FoundryVTT#1]
Hello!

Do you plan to update this system to last Foundry VTT version?
Because now it's showing "Compatibility Risk" badge ;(

**Comment by mvdleden** [comment]
Hi,

A new update is not planned in the near future. But afaik this system is
still completely compatible.
But your question got me thinking I should just update the version, so that
it shows it is compatible. I'll look into this.

Thanks.

Menno

**Comment by mvdleden** [comment]
Hi,

Just to let you know. I created a new version that is compatible with the upcoming 0.8.5 release.

**Comment by umren** [comment]
thx
